version: 2
updates:
- package-ecosystem: docker
  directory: "/nightscout"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - marciogranzotto
  assignees:
  - marciogranzotto
