name: Test Docker build

on: [pull_request]

jobs:
  dockerlint:
    name: Dockerfile linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hadolint
        run: docker run --rm -i hadolint/hadolint < nightscout/Dockerfile
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    needs: [dockerlint]
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            nightscout/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build amd64 image
        run: docker run --rm --privileged	-v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder	-t nightscout	--amd64 --test
  build-armv7:
    name: Build armv7 image
    runs-on: ubuntu-latest
    needs: [dockerlint]
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            nightscout/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build armv7 image
        run: docker run --rm --privileged	-v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder	-t nightscout	--armv7 --test
  build-aarch64:
    name: Build aarch64 image
    runs-on: ubuntu-latest
    needs: [dockerlint]
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            nightscout/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build aarch64 image
        run: docker run --rm --privileged	-v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder	-t nightscout	--aarch64 --test
  build-i386:
    name: Build i386 image
    runs-on: ubuntu-latest
    needs: [dockerlint]
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            nightscout/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build i386 image
        run: docker run --rm --privileged	-v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder	-t nightscout	--i386 --test
